[build]
  # 构建命令
  command = "npx playwright install --with-deps chromium && npm run build"
  # 构建输出目录
  publish = "dist"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "20"

# 首页重定向到博客文章页面
[[redirects]]
  from = "/"
  to = "/blog/posts/"
  status = 301

# SPA 路由重定向规则 - 处理客户端路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 处理 404 页面
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# 处理静态资源缓存
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
